name: Devrel News
on:
  schedule:
    - cron: '*/60 * * * *'
jobs:
  Build-HTML:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: ls
      - run: node --version
      - run: npm install
      - run: node ./render.js
      - run: bash ./build-html.sh
      - run: git status
      - run: git config --global user.email "jamesrobertsongittransfer@outlook.com"
      - run: git config --global user.name "james-a-rob"
      - run: git add -A
      - run: git commit -m "trigger-build"
      - run: git pull origin main
      - run: git push origin main